### ISSUE TITLE
how to change certain host to another dev host

### ISSUE THREAD

**Issue by futurist** [hatoo/http-mitm-proxy#11]
There's very common use case to use MITM to map to target URL to another dev url, to simulate online website behavior, like below rule of [whistle](https://wproxy.org/whistle/):

```
https://online.com/ http://localhost:3000/  excludeFilter://*/api
```

After setup the proxy, just browser https://online.com/ to start development, but I cannot figure out how to do with this repo.

**Comment by hatoo** [comment]
Hi, thanks for your issue!

I added support for modifying a URL.
You can check the test codes to see how to use them.

HTTP:
https://github.com/hatoo/http-mitm-proxy/blob/6d68167547e61368bd213e02e4f97c3c0603998d/tests/test.rs#L300-L324
HTTPS:
https://github.com/hatoo/http-mitm-proxy/blob/6d68167547e61368bd213e02e4f97c3c0603998d/tests/test.rs#L489-L525

**Comment by futurist** [comment]
I've tried https connect but panic at below line:
```rust
     *comm.request.uri_mut() = format!("127.0.0.1:{}", setup.server_port).parse().unwrap(); 
```

the error is:
```
called `Result::unwrap()` on an `Err` value: InvalidUriParts(InvalidUri(SchemeMissing))
```

**Comment by hatoo** [comment]
Hmm, it's odd.

Could you provide a complete source?

**Comment by futurist** [comment]
Sure it's odd, I've tried one more time and the above panic gone, but the proxy cannot run correctly, the source code is modified from `example/proxy.rs`, and the core part of code:

```rust
    while let Some(mut comm) = communications.next().await {
        let uri = comm.request.uri().clone();
        println!("original uri:{}", uri);
        if comm.request.method() == "CONNECT" {
            *comm.request.uri_mut() = format!("127.0.0.1:{}", 13000).parse().unwrap();
        } else {
            comm.request.headers_mut().insert(
                http::header::HOST,
                http::HeaderValue::from_bytes(format!("127.0.0.1:{}", 13000).as_bytes()).unwrap(),
            );
            *comm.request.uri_mut() = format!("http://127.0.0.1:{}", 13000).parse().unwrap();
        }
        println!("--------{:?}", &comm.request);
        // modify the request here if you want
        let _ = comm.request_back.send(comm.request);
    }
```

It's extracted from test.rs and moved into example, the question now is:

- how to setup a fullly working dev proxy both for HTTP and HTTPS connections?
- can add a example for this purpose?

**Comment by hatoo** [comment]
Just in case, are you using v0.6.1?

**Comment by hatoo** [comment]
I've added an example for it.
https://github.com/hatoo/http-mitm-proxy/blob/master/examples/dev_proxy.rs
I made some changes to the library and it's not released to carets.io.

I hope this helps you.

**Comment by futurist** [comment]
Thank you for the update, and I've just tried, with no luck.
What I'm looking for is something like goproxy as below logic but in Rust:

https://github.com/futurist/goproxy/blob/futurist-patch-1/examples/goproxy-customca/main.go

The go version is very straight forward, hope the rust version also very easy to config.

**Comment by hatoo** [comment]
Ok, I think you want to change a proxy HTTPS connection to an HTTP one.
It had not been implemented and I've implemented it now.

Could you check
https://github.com/hatoo/http-mitm-proxy/blob/master/examples/dev_proxy.rs
again?

**Comment by futurist** [comment]
Sorry, I've tried and still with no luck, the step below showed the issue:

## 1. Use [whistle](https://github.com/avwo/whistle) as chrome proxy, the result is like below:
![image](https://github.com/hatoo/http-mitm-proxy/assets/159167/1b1be736-630e-457c-a784-ae4e1dd98ef3)

The configed rule for whistle as below: (it's very easy to understand)

```
www.marscode.com/ide/ http://localhost:3333/
```


## 2. Use http-mitm-proxy dev_proxy.rs as browser proxy:

Use dev_proxy.rs (changed the `dev.example` into `www.marscode.com`), the sceen shown below:

![image](https://github.com/hatoo/http-mitm-proxy/assets/159167/fc164522-eb60-4f88-842b-0676f0f6b01b)

As you see the result showed the host become `[No Host]`

**Comment by hatoo** [comment]
All right, you want to change URL for specific path on HTTPS which was not supported.

I've done something on #16.
You can try the codes below.
I think it works like [whistle](https://github.com/avwo/whistle) with the your rule.

```rust
        // Forward connection from http/https www.marscode.com/ide/ to http://127.0.0.1:3333
        if req.uri().host() == Some("www.marscode.com")
            && req.method() != hyper::Method::CONNECT
            && req.uri().path().starts_with("/ide/")
        {
            req.headers_mut().insert(
                hyper::header::HOST,
                hyper::header::HeaderValue::from_maybe_shared(format!("127.0.0.1:{}", port))
                    .unwrap(),
            );

            let mut parts = req.uri().clone().into_parts();
            parts.scheme = Some(hyper::http::uri::Scheme::HTTP);
            parts.authority = Some(
                hyper::http::uri::Authority::from_maybe_shared(format!("127.0.0.1:{}", port))
                    .unwrap(),
            );
            parts.path_and_query = Some(
                parts
                    .path_and_query
                    .unwrap()
                    .to_string()
                    .trim_start_matches("/ide")
                    .parse()
                    .unwrap(),
            );
            *req.uri_mut() = hyper::Uri::from_parts(parts).unwrap();
        }
```

**Comment by futurist** [comment]
Thank you for the quick reply. I've just tried and it works as expected! Good job!

With 2 small things remained:
1. The certification generated is weak, better to enforce, like [this](https://github.com/omjadas/hudsucker/blob/main/examples/openssl.rs), e.g. use X509 and 4096 bits etc.
2. When setup as browser HTTP proxy, visit [google](https://www.google.com) always slow or with a long time blank page, does anything can do in the proxy layer to improve this? (I use the hudsucker's CA)

**Comment by hatoo** [comment]
Great 😄 

>     1. The certification generated is weak, better to enforce, like [this](https://github.com/omjadas/hudsucker/blob/main/src/certificate_authority/openssl_authority.rs), e.g. use X509 and 4096 bits etc.

Certification generating is out of the scope of this library, the `fn make_root_cert()` is just an example and I want to stick with `rcgen`'s default setting for simplicity.

>     2. When setup as browser HTTP proxy, visit [google](https://www.google.com) always slow or with a long time blank page, does anything can do in the proxy layer to improve this? (I use the hudsucker's CA)

The below code in the example enforces communications serial.
You can comment it out for speed and it should be noticeably faster.
```rust
if let Ok(Ok(mut response)) = comm.response.await {
            let mut len = 0;
            let body = response.body_mut();
            while let Some(frame) = body.next().await {
                if let Ok(frame) = frame {
                    if let Some(data) = frame.data_ref() {
                        len += data.len();
                    }
                }
            }
            println!(
                "{}\t{} -> {}\t{}\t{}",
                comm.client_addr,
                original_url,
                uri,
                response.status(),
                len
            );
        }
```

And are you running on a release build? (Just in case)

> Besides, I've noticed from curl output that some h2 protocol will become http/1.1 after proxy, but it's not a problem for me now.

Yes, I want to fix it.

**Comment by futurist** [comment]
yes I use the command `cargo run --release --example ...`  to run, it should be same as release.
