### ISSUE TITLE
[ASKING] what does mitm means?

### ISSUE THREAD

**Issue by KunalSin9h** [hatoo/http-mitm-proxy#2]

**Comment by hatoo** [comment]
I'm using mitm stands for man-in-the-middle.
https://en.wikipedia.org/wiki/Man-in-the-middle_attack

I used this term to indicate this proxy can read HTTPS traffic (with permission).

**Comment by KunalSin9h** [comment]
thanks @hatoo 

one more thing

when i am using the proxy server with `https` then i am getting this error

![image](https://github.com/hatoo/http-mitm-proxy/assets/82411321/85d00fde-9a00-4d62-a1d4-1482a0cfa925)

but using `http` works

![image](https://github.com/hatoo/http-mitm-proxy/assets/82411321/0d70b419-f8e0-4476-b10e-97ff57614f6c)

**Comment by hatoo** [comment]
Thanks for reporting!

It should be
```
-x http://127.0.0.1:3003 
```
(http to proxy, not https)

I fixed the document. Thank you!
