### ISSUE TITLE
how to fork many proxy threads?

### ISSUE THREAD

**Issue by futurist** [hatoo/http-mitm-proxy#41]
I've tested the speed, if I put a nginx proxy and reverse many http-mitm-proxy instance, the speed if very good than single one. like below config:

```
stream {
    upstream mitm {
        server 127.0.0.1:3103;
        server 127.0.0.1:3104;
        server 127.0.0.1:3105;
    }
    server {
        listen     3003;
        proxy_pass mitm;
    }
}
```

The question: how to config this lib fork a pool to handle incoming proxy request for speed?

**Comment by hatoo** [comment]
It's interesting.
https://github.com/hatoo/http-mitm-proxy/blob/de0744ef966b27ce01ec5a8c13923f73f0dbf1f8/src/lib.rs#L67
Proxy servers already run on multi threads.
So forking proxies on multiple ports should not very effective.
I'll investigate it.

> The question: how to config this lib fork a pool to handle incoming proxy request for speed?

if you want to run multiple proxy servers, just `tokio::spawn` server futures.
I don't know the best answer to run a TCP-level load balancer for those proxies on Rust though.

**Comment by futurist** [comment]
I've tested, the nginx version is more fast.

Maybe it's the (tx, rx) channel blocked the speed?

**Comment by hatoo** [comment]
what version are you using? is it including #40?

**Comment by futurist** [comment]
Noop, it's the version before #40.

Since #40 has API changed, I'll change my code later and do another test again.

**Comment by futurist** [comment]
I've test #40 and it's worked, the speed is good and better than previous version. Thank you for the work!
